### ISSUE TITLE
 MatplotlibDeprecationWarning: pyplot.hold is deprecated.

### ISSUE THREAD

**Issue by linusg** [ITGlobal/MatplotlibCS#10]
When running the server manually (had some other bugs in `matplotlib_cs.py`) and keeping track of the output, I see this:

```
MatplotlibCS\line_2d.py:32: MatplotlibDeprecationWarning: pyplot.hold is deprecated.
    Future behavior will be consistent with the long-time default:
    plot commands add elements without first clearing the
    Axes and/or Figure.
  plot.hold(True)
```

Solution would be removing the `plot.hold` call, as the new behaviour is consistent without it. I'll create a PR for that.

**Comment by plkn** [comment]
Fixed
