### ISSUE TITLE
Properly "close" plots created with onlySaveImage = false

### ISSUE THREAD

**Issue by linusg** [ITGlobal/MatplotlibCS#7]
When creating multiple plots, say two with `onlySaveImage = true` and then one with `onlySaveImage = false`, I get all three plots shown, in my understanding it should only open the last of my three plots in a window (I save the first two to "real" locations, the last one to a temporary file, due to the lack of an "only show, don't save" option).

Putting `plot.close("all")` [here](https://github.com/ITGlobal/MatplotlibCS/blob/master/MatplotlibCS/Python/matplotlib_cs.py#L69) does solve the problem for me.

```python
if not task["onlySaveImage"]:
    plot.show()

plot.close("all")
```

What do you think?

**Comment by plkn** [comment]
Hey,

Haven't returned to this project for a long time.  

> lack of an "only show, don't save" option

Judging from this line 

`if "filename" in task and task["filename"] is not None:`

if you will left FileName empty in C#, then it won't try to save to file.

And I think you are right about `plot.close("all")`.

Would you like to create a pull request with this fix?

**Comment by linusg** [comment]
> if you will left FileName empty in C#, then it won't try to save to file.

Good to know! That's because it [defaults to `null`](https://github.com/ITGlobal/MatplotlibCS/blob/master/MatplotlibCS/Figure.cs#L54), right? So omitting the argument completely will not save the file... Thanks!

> Would you like to create a pull request with this fix?

We use this at work, but of course I can find some spare time today/tomorrow and create the PR. Thanks for the super fast response, good to see that there's still someone looking on this project!

**Comment by linusg** [comment]
Thanks for merging! If I have any further questions those will probably come up on monday...
